[versions]
activity-ktx = "1.10.1"
android-build-gradle = "8.9.2"
annotation = "1.9.1"
appcompat = "1.7.0"
billing-ktx = "7.1.1"
build_tools = "35.0.1"
cmake = "3.22.1"
compile_sdk = "35"
compose-bom = "2025.04.01"
constraintlayout = "2.2.1"
core-ktx = "1.15.0"
drawerlayout = "1.2.0"
espresso-core = "3.6.1"
fragment-ktx = "1.8.6"
games-frame-pacing = "2.1.2"
gson = "2.13.1"
hilt = "2.56.2"
hilt-navigation-compose = "1.2.0"
jsoup = "1.19.1"
junit = "4.13.2"
junit-version = "1.2.1"
kotlin = "2.1.20"
kotlinx-coroutines-android = "1.10.1"
kotlinx-serialization-json = "1.8.0"
lifecycle-runtime = "2.8.7"
material = "1.12.0"
min_sdk = "23"
navigation = "2.8.9"
ndk = "28.1.13356709"
okhttp = "4.12.0"
retrofit = "2.11.0"
sentry-android = "8.5.0"
target_sdk = "35"
webkit = "1.13.0"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3-android" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-games-frame-pacing = { module = "androidx.games:games-frame-pacing", version.ref = "games-frame-pacing" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android" }

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
asset-pack = { id = "com.android.asset-pack" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref ="hilt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }