[versions]
activity-ktx = "1.12.2"
android-build-gradle = "8.13.2"
annotation = "1.9.1"
appcompat = "1.7.1"
billing-ktx = "8.3.0"
build_tools = "36.0.0"
cmake = "3.22.1"
compile_sdk = "36"
compose-bom = "2026.01.00"
constraintlayout = "2.2.1"
core-ktx = "1.17.0"
drawerlayout = "1.2.0"
espresso-core = "3.7.0"
firebase-bom = "34.7.0"
fragment-ktx = "1.8.9"
games-frame-pacing = "2.1.3"
google-services = "4.4.4"
gson = "2.13.2"
hilt = "2.58"
hilt-androidx = "1.3.0"
jsoup = "1.21.2"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin = "2.3.0"
kotlinx-coroutines-android = "1.10.2"
ksp = "2.3.2"
lifecycle-runtime = "2.10.0"
material = "1.13.0"
min_sdk = "23"
ndk = "29.0.14206865"
okhttp = "5.3.2"
retrofit = "3.0.0"
sentry-android = "8.30.0"
target_sdk = "36"
webkit = "1.15.0"
navigation3 = "1.0.0"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3-android" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-games-frame-pacing = { module = "androidx.games:games-frame-pacing", version.ref = "games-frame-pacing" }
androidx-hilt-lifecycle-viewmodel-compose = { module = "androidx.hilt:hilt-lifecycle-viewmodel-compose", version.ref = "hilt-androidx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-androidx" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry-android" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
asset-pack = { id = "com.android.asset-pack" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref ="hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref ="ksp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
